framework:
    http_client:
        default_options:
            timeout: 10
            max_duration: 20
            max_redirects: 5
            headers:
                User-Agent: '%app.http_user_agent%'
